# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site  站点配置
title: Shadow'S Site
subtitle: 心之所愿，无所不至！
description: Nothing is Impossible for a Willing Heart!
author: shadow
email: shadow000902@gmail.com
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://shadow000902.space
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory 目录配置
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang   # 国际化文件夹
skip_render:

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
#google_site_verification:

# Google Analytics
#google_analytics:

# CNZZ count
#cnzz_siteid:


# Make duoshuo show UA
# user_id must NOT be null when admin_enable is true!
# you can visit http://dev.duoshuo.com get duoshuo user id.
duoshuo_info:
  ua_enable: false
  admin_enable: false
  user_id: 0
  #admin_nickname: ROOT


# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true


# Show number of visitors to each article.
# You can visit https://leancloud.cn get AppID and AppKey.
leancloud_visitors:
  enable: false
  app_id: #<app_id>
  app_key: #<app_key>

leancloud_counter_security:
  enable_sync: true
  app_id: qjdKXm0RH80J6HWCj1X3DREC-gzGzoHsz
  app_key: 4rSep9EijQDvdmVi5cPCzgxz
  username: shadow000902@gmail.com #  Will be asked while deploying if is left blank
  password: TaoYi620120 #  Recommmended to be left blank. Will be asked while deploying if is left blank

# Tencent analytics ID
# tencent_analytics:

#algolia:
#  applicationID: '0HPI7IYB5V'
#  apiKey: 'c41b4c8f05b63867c231cd2ef194a34f'
#  adminApiKey: 'dbb0d7d98ccc80045798269262d29ab5'
#  indexName: 'Hexo_search'
#  chunkSize: 5000
#  fields:
#    - title
#    - slug
#    - content:strip

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Writing 写作配置
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:    # 代码块的设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag  分类&标签
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination  分页
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions  扩展
Plugins:
  hexo-algolia
  hexo-algoliasearch
  hexo-clean-css
  hexo-deployer-git
  hexo-generator-archive
  hexo-generator-baidu-sitemap
  hexo-generator-category
  hexo-generator-feed
  hexo-generator-index
  hexo-generator-seo-friendly-sitemap
  hexo-generator-sitemap
  hexo-generator-tag
  hexo-html-minifier
  hexo-renderer-ejs
  hexo-renderer-marked
  hexo-renderer-stylus
  hexo-server
  hexo-uglify

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

## Themes: https://hexo.io/themes/
theme: NexT


# Deployment  部署到Github
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: https://github.com/shadow000902/shadow000902.github.io.git,master
    coding: https://git.coding.net/shadow000902/shadow000902.coding.me.git,master
